TEST_VALUE:
   name: "test001"

MYSQL_CONFIG:
  name: "user"                       # 自定义次数据库链接名称
  type: "mysql"                        # 数据库链接类型
  host: "localhost"                   # 数据库链接地址
  port: 3306
  username: "root"                   # 数据库链接用户名
  password: "XXXXXX"                 # 数据库链接密码
  database: "users"                   # 数据库名
  entities: "mysql"                  # 自定义加载类型                 # 数据库打印日志
  synchronize: true                  # 是否开启同步数据表功能
